export const AQI = {
	"good":{
		aqi:[0,50],
		color:"#009966"
	},
	"moderate":{
		aqi:[51,100],
		color:"#FFDE33"
	},
	"unhealthy for sensitive groups":{
		aqi:[101,150],
		color:"#FF9933"
	},
	"unhealthy":{
		aqi:[151,200],
		color:"#CC0033"
	},
	"very unhealthy":{
		aqi:[201,300],
		color:"#660099"
	},
	"hazardous":{
		aqi:[300,1000],
		color:"#7E0023"
	}
}

export const REGIONS = {

	"Eur HI":"europe",
	"Eur LMI":"europe",
	"Wpr LMI":"asia",
	"Afr":"africa",
	"Sear":"asia",
	"Wpr HI":"oceania",
	"Amr LMI":"samerica",
	"Amr HI":"namerica",
	//"Amr LMI":"americas",
	//"Amr HI":"americas",
	"Emr HI":"middle_east",
	"Emr LMI":"asia"

}

export const REGION_NAMES = ["namerica","samerica","europe","africa","middle_east","asia","oceania"]

export const REGION_COUNTRY = {
     "Algeria":"africa",
     "Angola":"africa",
     "Benin":"africa",
     "Botswana":"africa",
     "Burkina":"africa",
     "Burundi":"africa",
     "Cameroon":"africa",
     "Cape Verde":"africa",
     "Central african Republic":"africa",
     "Chad":"africa",
     "Comoros":"africa",
     "Congo":"africa",
     "Congo, Democratic Republic of":"africa",
     "Djibouti":"africa",
     "Egypt":"middle_east",
     "Equatorial Guinea":"africa",
     "Eritrea":"africa",
     "Ethiopia":"africa",
     "Gabon":"africa",
     "Gambia":"africa",
     "Ghana":"africa",
     "Guinea":"africa",
     "Guinea-Bissau":"africa",
     "Ivory Coast":"africa",
     "Kenya":"africa",
     "Lesotho":"africa",
     "Liberia":"africa",
     "Libya":"africa",
     "Madagascar":"africa",
     "Malawi":"africa",
     "Mali":"africa",
     "Mauritania":"africa",
     "Mauritius":"africa",
     "Morocco":"africa",
     "Mozambique":"africa",
     "Namibia":"africa",
     "Niger":"africa",
     "Nigeria":"africa",
     "Rwanda":"africa",
     "Sao Tome and Principe":"africa",
     "Senegal":"africa",
     "Seychelles":"africa",
     "Sierra Leone":"africa",
     "Somalia":"africa",
     "South Africa":"africa",
     "South Sudan":"africa",
     "Sudan":"africa",
     "Swaziland":"africa",
     "Unit. Rep. of Tanzania":"africa",
     "Togo":"africa",
     "Tunisia":"africa",
     "Uganda":"africa",
     "Zambia":"africa",
     "Zimbabwe":"africa",
     "Afghanistan":"asia",
     "Bahrain":"middle_east",
     "Bangladesh":"asia",
     "Bhutan":"asia",
     "Brunei":"asia",
     "Myanmar":"asia",
     "Cambodia":"asia",
     "China":"asia",
     "East Timor":"asia",
     "India":"asia",
     "Indonesia":"asia",
     "Iran (Islamic Republic of)":"middle_east",
     "Iraq":"middle_east",
     "Israel":"middle_east",
     "Japan":"asia",
     "Jordan":"middle_east",
     "Kazakhstan":"asia",
     "Korea, North":"asia",
     "Republic of Korea":"asia",
     "Kuwait":"middle_east",
     "Kyrgyzstan":"asia",
     "Laos":"asia",
     "Lebanon":"middle_east",
     "Malaysia":"asia",
     "Maldives":"asia",
     "Mongolia":"asia",
     "Nepal":"asia",
     "Oman":"middle_east",
     "Pakistan":"asia",
     "Philippines":"asia",
     "Qatar":"middle_east",
     "Russian Federation":"europe",
     "Saudi Arabia":"middle_east",
     "Singapore":"asia",
     "Sri Lanka":"asia",
     "Syria":"middle_east",
     "Tajikistan":"asia",
     "Thailand":"asia",
     "Turkey":"europe",
     "Turkmenistan":"asia",
     "United Arab Emirates":"middle_east",
     "Uzbekistan":"asia",
     "Vietnam":"asia",
     "Yemen":"middle_east",
     "Albania":"europe",
     "Andorra":"europe",
     "Armenia":"europe",
     "Austria":"europe",
     "Azerbaijan":"europe",
     "Belarus":"europe",
     "Belgium":"europe",
     "Bosnia and Herzegovina":"europe",
     "Bulgaria":"europe",
     "Croatia":"europe",
     "Cyprus":"europe",
     "Czech Republic":"europe",
     "Denmark":"europe",
     "Estonia":"europe",
     "Finland":"europe",
     "France":"europe",
     "Georgia":"europe",
     "Germany":"europe",
     "Greece":"europe",
     "Hungary":"europe",
     "Iceland":"europe",
     "Ireland":"europe",
     "Italy":"europe",
     "Latvia":"europe",
     "Liechtenstein":"europe",
     "Lithuania":"europe",
     "Luxembourg":"europe",
     "The former Yugoslav Republic of Macedonia":"europe",
     "Malta":"europe",
     "Moldova":"europe",
     "Monaco":"europe",
     "Montenegro":"europe",
     "Netherlands":"europe",
     "Norway":"europe",
     "Poland":"europe",
     "Portugal":"europe",
     "Romania":"europe",
     "San Marino":"europe",
     "Serbia":"europe",
     "Slovakia":"europe",
     "Slovenia":"europe",
     "Spain":"europe",
     "Sweden":"europe",
     "Switzerland":"europe",
     "Ukraine":"europe",
     "United Kingdom":"europe",
     "Vatican City":"europe",
     "Antigua and Barbuda":"namerica",
     "Bahamas":"namerica",
     "Barbados":"namerica",
     "Belize":"namerica",
     "Canada":"namerica",
     "Costa Rica":"namerica",
     "Cuba":"namerica",
     "Dominica":"namerica",
     "Dominican Republic":"namerica",
     "El Salvador":"namerica",
     "Grenada":"namerica",
     "Guatemala":"namerica",
     "Haiti":"namerica",
     "Honduras":"namerica",
     "Jamaica":"namerica",
     "Mexico":"namerica",
     "Nicaragua":"namerica",
     "Panama":"namerica",
     "Saint Kitts and Nevis":"namerica",
     "Saint Lucia":"namerica",
     "Saint Vincent and the Grenadines":"namerica",
     "Trinidad and Tobago":"namerica",
     "United States of America":"namerica",
     "Australia":"oceania",
     "Fiji":"oceania",
     "Kiribati":"oceania",
     "Marshall Islands":"oceania",
     "Micronesia":"oceania",
     "Nauru":"oceania",
     "New Zealand":"oceania",
     "Palau":"oceania",
     "Papua New Guinea":"oceania",
     "Samoa":"oceania",
     "Solomon Islands":"oceania",
     "Tonga":"oceania",
     "Tuvalu":"oceania",
     "Vanuatu":"oceania",
     "Argentina":"samerica",
     "Bolivia, Plurinational States of":"samerica",
     "Brazil":"samerica",
     "Chile":"samerica",
     "Colombia":"samerica",
     "Ecuador":"samerica",
     "Guyana":"samerica",
     "Paraguay":"samerica",
     "Peru":"samerica",
     "Suriname":"samerica",
     "Uruguay":"samerica",
     "Venezuela, Bolivarian Republic of":"samerica"
}